apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app:gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: python-app-gcp-devops-gke
        image: 'gcr.io/terraform-tutorials1/gcpdevops'
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"